### ISSUE TITLE
Stored Procedure in Microsoft SQL Server

### ISSUE THREAD

**Issue by cmendesce** [naskarlab/wsplsqljson#1]
Hi, 

Are you planning to code this same feature for Microsoft SQL Server?

**Comment by rafaeluchoa** [comment]
I never tested with the SQL Server, but I think that it works. 

The only dependency of the Oracle driver is the support for some types as OracleTypes.CURSOR and OracleTypes.BLOB.

https://github.com/naskarlab/wsplsqljson/blob/master/src/main/java/com/naskar/pls/service/impl/StoredProcedureServiceImpl.java

You can configure the SQL Server datasource that it must work.
